[SDRAN-1426] New plugin format
onosproject/onos-helm-charts pull request #588
Opened 2022-01-20 23:59 UTC by teone

2022-01-23 20:31 UTC, adibrastegarnia approved these changes
Can we merge this @teone ?

2022-01-24 00:13 UTC, adibrastegarnia requested changes

2022-01-24 00:13 UTC, adibrastegarnia commented on onos-config/Chart.yaml
> +appVersion: v0.10.11
We should match app version with image tag version

2022-01-24 16:38 UTC, tomikazi approved these changes

2022-01-24 16:39 UTC, merged