Migrate onos-topo and onos-config to Atomix runtime
onosproject/onos-helm-charts pull request #690
Opened 2022-10-28 07:02 UTC by kuujo

2022-10-28 18:13 UTC, adibrastegarnia requested changes

2022-10-28 18:13 UTC, adibrastegarnia commented on onos-config/templates/storageprofile.yaml
> +apiVersion: atomix.io/v3beta3
add license header

2022-10-28 18:13 UTC, adibrastegarnia commented on onos-topo/templates/storageprofile.yaml
> +apiVersion: atomix.io/v3beta3
add license header

2022-11-08 20:50 UTC, ray-milkey approved these changes

2022-11-08 21:02 UTC, merged